sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '6'
before_install:
  - npm i -g npm@latest
before_script:
  - npm run lint
script:
  - npm run build
after_success:
  - npm run autorelease
branches:
  except:
    - "master"
